### ISSUE TITLE
show benchmark in comparison to cruby

### ISSUE THREAD

**Issue by grosser** [sisshiki1969/ruruby#12]
much easier to see how far along this is when comparing to cruby instead of "nsec/inst"

so ideally show just 10% slower/faster instead of the raw numbers

**Comment by sisshiki1969** [comment]
Thanks for your attention.
Currently, ruruby's performance in speed is not satisfactory.
Here is a preliminary report:

|  benchmark            |     ruruby    |   CRuby(2.8.0)   |
|----------------------|:------------:|:-----------------:|
|  so_mandelbrot.rb*  |    2.88 s     |        1.89 s          |
|  app_mandelbrot.rb* |    6.83 s    |         2.35 s         |
|  app_aobench.rb*    |   27.96 s    |         9.01 s         |
|  app_fib.rb*              |     1.51 s    |         0.32 s         |
|  optcarrot**             |    19.68 s    |         4.05 s         |

Execution time in seconds are shown.
The lower, the better.
  *available on https://github.com/ruby/ruby/blob/master/benchmark/
  **Optcarrot is NES emulator, and a semi-official benchmark program for Ruby, which is available on https://github.com/mame/optcarrot

Optcarrot benchmark result
|  benchmark          |     ruruby    |  CRuby(2.8.0)  |
|-------------------- |:------------:|:----------------:|
|  optcarrot             |    9.62 fps   |       48.8 fps     |

Frames per seconds are shown.
The higher, the better.

**Comment by grosser** [comment]
Pretty promising results, would still be nice to see them on the readme,
maybe with info on what performance targets are / if performance is not a
goal.

**Comment by sisshiki1969** [comment]
Thanks.
README was updated.
The performance goal is CRuby(MRI).....,  but I'm typical Japanese and too shy to write such a thing....

**Comment by grosser** [comment]
awesome! :D
