### ISSUE TITLE
show memory usage for benchmark

### ISSUE THREAD

**Issue by grosser** [sisshiki1969/ruruby#13]
if it uses very little memory (compare against mruby/cruby) that could be an interesting usecase

**Comment by sisshiki1969** [comment]
Thank you for advice.
We don't have a garbage collector implemented yet, so we can't make a fair comparison about that point at this time.
It is issue in the future.

**Comment by grosser** [comment]
could compare against cruby with GC turned off for now ?

**Comment by sisshiki1969** [comment]
I've checked memory consumption with gnu-time..

#### benchmark: app_aobench.rb
(producing and consuming huge number of objects)
| engine |max resident set size|
|-----------------|:---------:|
| CRuby(GC on) | 15 MB   |
| CRuby(GC off) |1649 MB|
| ruruby  |  3864 MB   |

#### benchmark: fibo.rb
(producing almost no objects, huge number of method calls)
| engine |max resident set size|
|-----------------|:---------:|
| CRuby(GC on) | 13.7 MB   |
| CRuby(GC off) | 13.9 MB|
| ruruby  |  2.1 MB   |

#### benchmark: optcarrot (benchmark mode)
(a lot of arithmetic and array operations)
| engine |max resident set size|
|-----------------|:---------:|
| CRuby(GC on) | 82.5 MB   |
| CRuby(GC off) | 85.5 MB|
| ruruby  |  355.6 MB   |

**Comment by grosser** [comment]
thx, the no objects case looks promising :)
