### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jtran** [sisshiki1969/ruruby#21]
Hi, I would love to use Ruby as a scripting language for making games with Rust.  Ruruby is great for integrating Ruby with Rust.  But for this use case, I need it to run cross-platform.  It currently fails to build in `coroutine.rs`.  There's no conditional compilation for the `asm` module that runs on Windows.  Is there any plan to support Windows?

**Comment by jtran** [comment]
I got it building on Windows, but running into a segfault when I try to run the tests.  I'm not too familiar with assembly, so it might be something simple.  I would appreciate any help.  Thanks.

https://github.com/sisshiki1969/ruruby/compare/master...jtran:windows

**Comment by jtran** [comment]
I think I figured out the issue.  PR incoming for Windows x64.  I just want to fix the tests.  There are things like path separators that need to change from `/` to `\` and also some minor floating point differences.

**Comment by sisshiki1969** [comment]
Thank you for comments and PR!
And sorry for my late response.
I'll check it soon.
