### ISSUE TITLE
UB in ident table

### ISSUE THREAD

**Issue by lopopolo** [sisshiki1969/ruruby#28]
`IdentId` has an inner `NonZeroU32` member:

https://github.com/sisshiki1969/ruruby/blob/a21f215cd0d035b1c5d8df9b6ed9bbfd1809f1b3/ruruby-common/src/id_table.rs#L14

But the `<null>` ident is defined with symbol ID `0`:

https://github.com/sisshiki1969/ruruby/blob/a21f215cd0d035b1c5d8df9b6ed9bbfd1809f1b3/ruruby-common/src/id_table.rs#L158

`IdentId::from` should probably either be replaced with a `TryFrom` impl or an unsafe function like `IdentId::new_unchchecked`. `From` impls cannot be unsafe and ideally shouldn't have safety pre-conditions (which indicates that the fn should be `unsafe`).

**Comment by sisshiki1969** [comment]
Hi, Thank you for reading my code and giving me the issue!

Yes, as you may know, IdentId(0) is a kind of dummy data, and not expected to be accessed.
And this code seems to be inappropriate as you pointed out.

Fixed in #29.
